<template><h2 id="qu-est-ce-que-readmetrics" tabindex="-1"><a class="header-anchor" href="#qu-est-ce-que-readmetrics" aria-hidden="true">#</a> Qu'est-ce que ReadMETRICS ?</h2>
<p><strong>ReadMETRICS</strong> est une nouvelle solution clé en main pour :</p>
<ul>
<li>le suivi des accords de transformation, y compris avant et après</li>
<li>l'analyse de l'utilisation à travers les disciplines et les consortiums</li>
<li>l'évaluation de la valeur des dépenses d'édition</li>
<li>permettre une analyse comparative des citations</li>
</ul>
<p>Il est basé sur les outils libres et open source <a href="https://www.ezpaarse.org/" target="_blank" rel="noopener noreferrer">ezPAARSE<OutboundLink/></a> et <a href="https://ezmesure.couperin.org/" target="_blank" rel="noopener noreferrer">ezMESURE<OutboundLink/></a> déjà existants et testés sur le terrain, en étendant et en incluant des fonctionnalités inspirées par la transition de la <a href="https://bnl.public.lu/fr.html" target="_blank" rel="noopener noreferrer">Bibliothèque nationale du Luxembourg<OutboundLink/></a> vers l'Open Access, décrite <a href="https://www.consortium.lu/?page_id=6334" target="_blank" rel="noopener noreferrer">ici<OutboundLink/></a></p>
<iframe frameborder="0" style="width:100%;height:440px;" src="https://viewer.diagrams.net/?p=anim&highlight=0000ff&edit=_blank&layers=1&nav=1&title=2020-10-08-readmetrics-architecture.drawio#Uhttps%3A%2F%2Fdrive.google.com%2Fuc%3Fid%3D1-IVxBpzs6TXC1M-Q6pYoAu_OYUG2PQe1%26export%3Ddownload"> sss </iframe>
<h2 id="timeline" tabindex="-1"><a class="header-anchor" href="#timeline" aria-hidden="true">#</a> Timeline</h2>
<p>Nous travaillons à rendre ReadMETRICS <strong>disponible d'ici l'été 2021</strong>. En attendant, les outils qui constituent la pile sont déjà disponibles et peuvent être déployés et utilisés par les sites pilotes intéressés. N'hésitez pas à <a href="mailto:readmetrics@couperin.org">nous contacter</a> directement !</p>
<h2 id="financing-the-team-and-the-tools" tabindex="-1"><a class="header-anchor" href="#financing-the-team-and-the-tools" aria-hidden="true">#</a> Financing the Team and the Tools</h2>
<p>L'équipe compte actuellement 6 personnes, soutenues financièrement par l'Inist-CNRS et le consortium Couperin.org avec l'aide plus ponctuelle de structures tierces (BnL et OCLC). Parmi les institutions désireuses d'utiliser la solution readMETRICS, nous recherchons des partenaires prêts à participer financièrement, pour nous aider à financer deux des postes de développeurs actuels et continuer à maintenir les outils existants et à offrir de nouvelles fonctionnalités. Le montant que nous devons atteindre est d'environ 90k€ (ou 100k$) par an.</p>
<h2 id="qu-est-ce-que-ezpaarse" tabindex="-1"><a class="header-anchor" href="#qu-est-ce-que-ezpaarse" aria-hidden="true">#</a> Qu'est-ce que'ezPAARSE</h2>
<p>Un <a href="https://github.com/ezpaarse-project/ezpaarse/" target="_blank" rel="noopener noreferrer">logiciel libre<OutboundLink/></a> qui peut ingérer vos fichiers journaux (proxy) et montrer comment les utilisateurs accèdent aux ressources électroniques souscrites. Il filtre, extrait et enrichit les événements d'accès qui ont été repérés et produit un fichier de résultats qu'ezMESURE peut ingérer et afficher dans un tableau de bord.</p>
<h2 id="qu-est-ce-que-ezmesure" tabindex="-1"><a class="header-anchor" href="#qu-est-ce-que-ezmesure" aria-hidden="true">#</a> Qu'est-ce que'ezMESURE</h2>
<p>Un <a href="https://github.com/ezpaarse-project/ezmesure/" target="_blank" rel="noopener noreferrer">logiciel libre<OutboundLink/></a> basé sur <a href="https://www.elastic.co/fr/" target="_blank" rel="noopener noreferrer">Elastic et Kibana<OutboundLink/></a> pour constituer un répertoire centralisant les données statistiques d'utilisation produites par une ou plusieurs instances d'ezPAARSE. Il est également capable d'ingérer les données de <a href="https://www.projectcounter.org/code-of-practice-five-sections/abstract/" target="_blank" rel="noopener noreferrer">COUNTER5<OutboundLink/></a>.</p>
<p><img src="/readmetrics/images/ezmesure_dashboard.png" alt="ezMESURE Dashboard"></p>
</template>
